# 应用名称
spring.application.name=lwsys
# 数据库驱动：
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# 数据源名称
spring.datasource.name=defaultDataSource
# 数据库连接地址
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/test_journal?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
# 数据库用户名&密码：
spring.datasource.username=root
spring.datasource.password=123456
#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis.mapper-locations=classpath:mappers/*xml
#指定Mybatis的实体目录
#mybatis.type-aliases-package=com.example.dingcan_boot.mybatis.entity
# 应用服务 WEB 访问端口
server.port=8087


# 访问template 下的html文件需要配置模板，映射
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.content-type=text/html
spring.thymeleaf.mode=LEGACYHTML5
# 开发是关闭缓存，不然没法看到实时页面
spring.thymeleaf.cache=false

spring.mvc.hiddenmethod.filter.enabled=true

#spring.http.multipart.enabled=false
spring.servlet.multipart.enabled=false

#file.uploadFolder=D://petIMG//
# 对外访问的资源路径
#file.staticAccessPath=/upload/*

#r热部署
spring.devtools.restart.enabled=true
